### ISSUE TITLE
InternalOAuthError: failed to obtain access token

### ISSUE THREAD

**Issue by egrish** [passport/express-4.x-openidconnect-example#1]
After login (Log In with IdP) I have the following error:

InternalOAuthError: failed to obtain access token
    at /home/egris/express-4.x-openidconnect-example/node_modules/passport-openidconnect/lib/strategy.js:76:36
    at /home/egris/express-4.x-openidconnect-example/node_modules/oauth/lib/oauth2.js:177:18
    at ClientRequest.<anonymous> (/home/egris/express-4.x-openidconnect-example/node_modules/oauth/lib/oauth2.js:148:5)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at TLSSocket.socketErrorListener (_http_client.js:308:9)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1272:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)

The link in the browser contains:

/callback?code=7fe20c03-2a04-45a9-8f9b-f059960990f6&scope=openid&state&session_state=bf7fb79b-4c01-4cfb-ad63-3fabe16598fc

**Comment by notifyanand** [comment]
+1 Hitting the same issue

**Comment by notifyanand** [comment]
InternalOAuthError: failed to obtain access token
   at ~ /express-4.x-openidconnect-example-master/node_modules/passport-openidconnect/lib/strategy.js:76:36
   at ~ /express-4.x-openidconnect-example-master/node_modules/passport-openidconnect/node_modules/oauth/lib/oauth2.js:177:18
   at passBackControl (~ /express-4.x-openidconnect-example-master/node_modules/passport-openidconnect/node_modules/oauth/lib/oauth2.js:123:9)
   at IncomingMessage.<anonymous> (~ /express-4.x-openidconnect-example-master/node_modules/passport-openidconnect/node_modules/oauth/lib/oauth2.js:143:7)
   at emitNone (events.js:72:20)
   at IncomingMessage.emit (events.js:166:7)
   at endReadableNT (_stream_readable.js:913:12)
   at nextTickCallbackWith2Args (node.js:442:9)
   at process._tickCallback (node.js:356:17)
